
--duckdb dw_marts.duckdb -c ".read BUILD_DW_MARTS.sql"  

--STEP 1: DW- create star schema
.read 01_CREATE_TABLES_DW.sql

--STEP 2: DW_LOAD DATA FROM CSV FILES INTO TABLE
.read 02_LOAD_SCHEMA_DW.sql

-- STEP 3: CREATE FLAT MART
.read 03_CREATE_FLAT_MART.sql

-- STEP 4: CREATE FLAT MART
.read 04_CREATE_SKILLS_MART.sql

-- STEP 5: CREATE PRIORITY MART
.read 05_CREATE_PRIORITY_MART.sql

-- STEP 6: UPDATE PRIORIRT MART
.read 06_UPDATE_PRIORITY_MART.sql

-- STEP 7: MART - CREATE COMPANY MART
.read 07_CREATE_COMPANY_MART.sql